services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres:18-alpine
    container_name: database
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  migrator:
    image: migrate/migrate
    container_name: migrator
    networks:
      - backend
    volumes:
      - ./migrations:/migrations
    entrypoint: ["migrate"]
    depends_on:
      - database

volumes:
  pgdata:

networks:
  backend:
    driver: bridge