openapi: 3.0.4
info:
  title: "When Works API"
  description: "API documentation for the When Works scheduling system."
  version: "1.0.0"

servers:
  - url: "http://localhost:8080/api/v1"
    description: "Local development server"

security:
  - cookieAuth: []

paths:
  "/users":
    $ref: "./paths/users.yaml#/~1users"
  "/users/{userId}":
    $ref: "./paths/users.yaml#/~1users~1{userId}"
  "/login":
    $ref: "./paths/auth.yaml#/~1login"
  "/logout":
    $ref: "./paths/auth.yaml#/~1logout"

components:
  schemas:
    Role:
      $ref: "./components/schemas/role.yaml#/Role"
    User:
      $ref: "./components/schemas/user.yaml#/User"
    NewUser:
      $ref: "./components/schemas/user.yaml#/NewUser"
    UpdateUser:
      $ref: "./components/schemas/user.yaml#/UpdateUser"
    LoginRequest:
      $ref: "./components/schemas/auth.yaml#/LoginRequest"

  securitySchemes:
    cookieAuth:
      type: "apiKey"
      in: "cookie"
      name: "accessToken"
      description: "The API token stored in an HttpOnly cookie."
