openapi: 3.0.4
info:
  title: "When Works API"
  description: "API documentation for the When Works scheduling system."
  version: "1.0.0"

servers:
  - url: "http://localhost:8080/api/v1"
    description: "Local development server"

security:
  - cookieAuth: []

paths:
  "/roles":
    $ref: "./paths/roles.yaml#/~1roles"
  "/roles/{roleId}":
    $ref: "./paths/roles.yaml#/~1roles~1{roleId}"
  "/users":
    $ref: "./paths/users.yaml#/~1users"
  "/users/{userId}":
    $ref: "./paths/users.yaml#/~1users~1{userId}"
  "/auth/login":
    $ref: "./paths/auth.yaml#/~1login"
  "/auth/logout":
    $ref: "./paths/auth.yaml#/~1logout"
  "/auth/forgot-password":
    $ref: "./paths/auth.yaml#/~1auth~1forgot-password"
  "/auth/reset-password":
    $ref: "./paths/auth.yaml#/~1auth~1reset-password"
  "/account/profile":
    $ref: "./paths/account.yaml#/~1account~1profile"
  "/account/password":
    $ref: "./paths/account.yaml#/~1account~1password"

components:
  schemas:
    Permission:
      $ref: "./components/schemas/role.yaml#/Permission"
    Role:
      $ref: "./components/schemas/role.yaml#/Role"
    NewRole:
      $ref: "./components/schemas/role.yaml#/NewRole"
    UpdateRole:
      $ref: "./components/schemas/role.yaml#/UpdateRole"
    User:
      $ref: "./components/schemas/user.yaml#/User"
    NewUser:
      $ref: "./components/schemas/user.yaml#/NewUser"
    UpdateUser:
      $ref: "./components/schemas/user.yaml#/UpdateUser"
    LoginRequest:
      $ref: "./components/schemas/auth.yaml#/LoginRequest"
    UpdateProfileRequest:
      $ref: "./components/schemas/account.yaml#/UpdateProfileRequest"
    ChangePasswordRequest:
      $ref: "./components/schemas/account.yaml#/ChangePasswordRequest"

  securitySchemes:
    cookieAuth:
      type: "apiKey"
      in: "cookie"
      name: "accessToken"
      description: "The API token stored in an HttpOnly cookie."
